"""create tables students sessions violations

Revision ID: d6047dd4df86
Revises: 
Create Date: 2026-09-06 19:22:12.430529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6047dd4df86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.String(length=64), nullable=False),
    sa.Column('registered_photo_ref', sa.String(length=1024), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'PROCTOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_university_id'), 'students', ['university_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ENDED', name='session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_student_id'), 'sessions', ['student_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PHONE', 'PERSON', 'FACE_LOSS', 'HEAD_TURN', 'VOICE', 'NOISE', 'SCREEN_LEAVE', name='violation_type'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_contribution', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_violations_confidence_range'),
    sa.CheckConstraint('risk_contribution >= 0 AND risk_contribution <= 1', name='ck_violations_risk_contribution_range'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_session_id'), 'violations', ['session_id'], unique=False)
    op.create_index(op.f('ix_violations_timestamp'), 'violations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_violations_type'), 'violations', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_type'), table_name='violations')
    op.drop_index(op.f('ix_violations_timestamp'), table_name='violations')
    op.drop_index(op.f('ix_violations_session_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_sessions_student_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_students_university_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
